### ISSUE TITLE
Notify the user if he enters the password from `Yubikey` in another language

### ISSUE THREAD

**Issue by Danil42Russia** [VKCOM/admstorm#197]
<img width="386" alt="Снимок экрана 2023-08-03 в 17 53 07" src="https://github.com/VKCOM/admstorm/assets/6605618/9263eca7-0982-4fec-a3c6-9db51c4f7a24">

And to review the lettering, it seems to be a PIN, not a password

**Comment by Hidanio** [comment]
Pin, generally, only numbers
We can have characters and numbers. I think that 'password' - ok in this context
